name: connectanum_bench
description: Benchmark harness for the Connectanum router.
version: 3.0.0-beta
homepage: https://github.com/konsultaner/connectanum-dart
repository: https://github.com/konsultaner/connectanum-dart
issue_tracker: https://github.com/konsultaner/connectanum-dart/issues
false_secrets:
  - /test/wamp_transport_targets_test.dart
executables:
  router_bench:
  bench_router_service:
  wamp_client_worker:
environment:
  sdk: '^3.9.2'
dependencies:
  args: ^2.4.2
  cbor: ^6.3.7
  logging: ^1.2.0
  msgpack_dart: ^1.0.1
  yaml: ^3.1.2
  connectanum_router: ^3.0.0-beta
  connectanum_core: ^3.0.0-beta
  connectanum_client: ^3.0.0-beta
  connectanum_auth_server: ^3.0.0-beta
dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
resolution: workspace
