name: connectanum_workspace
environment:
  sdk: '^3.9.2'
hooks:
  user_defines:
    connectanum_client:
      CONNECTANUM_SKIP_NATIVE_BUILD: true
    connectanum_router:
      CONNECTANUM_SKIP_NATIVE_BUILD: true
workspace:
  - packages/connectanum_core
  - packages/connectanum_mcp
  - packages/connectanum_client
  - packages/connectanum_router
  - packages/connectanum_auth_server
  - packages/connectanum_bench
