import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:pointycastle/digests/sha256.dart';

const _expectedSha256 =
    'dcec617a2e1b700fa132d1583a186cb70611113395e869f2dd6cc82b415d3094';

void main(List<String> arguments) {
  if (arguments.length != 1) {
    stderr.writeln(
      'Usage: dart run tool/generate_scram_worker.dart <argon2.umd.min.js>',
    );
    exitCode = 64;
    return;
  }
  final input = File(arguments.single).readAsBytesSync();
  final digest = SHA256Digest().process(Uint8List.fromList(input));
  final actual = digest
      .map((byte) => byte.toRadixString(16).padLeft(2, '0'))
      .join();
  if (actual != _expectedSha256) {
    stderr.writeln('Unexpected hash-wasm input digest: $actual');
    exitCode = 65;
    return;
  }

  var library = utf8.decode(input);
  library = library.replaceFirst(
    'A.salt.length<8)throw new Error("Salt should be at least 8 bytes long")',
    'A.salt.length<1)throw new Error("Salt must not be empty")',
  );
  final worker =
      '''
$library
self.onmessage=async function(event){
  const data=event.data;
  const password=data.password;
  const salt=data.salt;
  try {
    let result;
    if(data.kdf==='argon2id13'){
      result=await hashwasm.argon2id({
        password:password,
        salt:salt,
        parallelism:1,
        iterations:data.iterations,
        memorySize:data.memory,
        hashLength:data.keyLength,
        outputType:'binary'
      });
    }else if(data.kdf==='pbkdf2'){
      const key=await crypto.subtle.importKey('raw',password,'PBKDF2',false,['deriveBits']);
      const bits=await crypto.subtle.deriveBits({
        name:'PBKDF2',
        salt:salt,
        iterations:data.iterations,
        hash:'SHA-256'
      },key,data.keyLength*8);
      result=new Uint8Array(bits);
    }else{
      throw new Error('Unsupported KDF');
    }
    password.fill(0);
    salt.fill(0);
    self.postMessage(result,[result.buffer]);
  }catch(_){
    password.fill(0);
    salt.fill(0);
    self.postMessage(null);
  }
};
''';
  final encoded = jsonEncode(worker).replaceAll(r'$', r'\$');
  File(
    'lib/src/authentication/scram_argon2_worker_source.g.dart',
  ).writeAsStringSync(
    '// Generated by tool/generate_scram_worker.dart from hash-wasm 4.12.0.\n'
    '// See third_party/hash-wasm/LICENSE.\n'
    'const String scramArgon2WorkerSource = $encoded;\n',
  );
}
