#!/usr/bin/env python3
"""Bundle every vendored WAMP fixture byte for VM and browser tests."""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FIXTURES = ROOT / "packages/connectanum_core/testdata/wamp_conformance"
OUTPUT = ROOT / "packages/connectanum_core/test/conformance/fixture_bundle.dart"
MANIFEST = OUTPUT.with_suffix(".json")


def collect(root: Path) -> dict[str, bytes]:
    if root.is_symlink() or not root.is_dir():
        raise ValueError("Fixture root must be a regular directory")
    files = {}

    def visit(directory: Path) -> None:
        for entry in sorted(directory.iterdir()):
            name = entry.relative_to(root).as_posix()
            if not re.fullmatch(r"[A-Za-z0-9_.\-/]+", name):
                raise ValueError("Unsupported fixture path: " + name)
            if entry.is_symlink():
                raise ValueError("Symlink in fixture inventory: " + name)
            if entry.is_dir():
                visit(entry)
            elif entry.is_file():
                files[name] = entry.read_bytes()
            else:
                raise ValueError("Non-regular fixture: " + name)

    visit(root)
    if not files:
        raise ValueError("Empty fixture inventory")
    return files


def render(files: dict[str, bytes]) -> bytes:
    # Encoding raw bytes preserves numeric spellings and Unicode in upstream JSON.
    lines = [
        "// Generated by tool/build_conformance_fixtures.py; do not edit.",
        "import 'dart:convert';",
        "",
        "const _fixtureBytes = <String, String>{",
    ]
    for name, content in sorted(files.items()):
        encoded = base64.b64encode(content).decode("ascii")
        lines.append(f"  '{name}':")
        chunks = [encoded[i:i + 72] for i in range(0, len(encoded), 72)] or [""]
        lines.extend("      '" + chunk + "'" for chunk in chunks)
        lines[-1] += ","
    lines.extend([
        "};",
        "",
        "Map<String, String> loadConformanceFixtures() => {",
        "  for (final entry in _fixtureBytes.entries)",
        "    entry.key: utf8.decode(base64.decode(entry.value)),",
        "};",
        "",
    ])
    return "\n".join(lines).encode("utf-8")


def build(root: Path, output: Path, manifest: Path, *, check: bool) -> int:
    files = collect(root)
    bundle = render(files)
    metadata = {
        "sourceHashes": {
            name: hashlib.sha256(content).hexdigest()
            for name, content in sorted(files.items())
        },
        "bundleSha256": hashlib.sha256(bundle).hexdigest(),
    }
    encoded_metadata = (json.dumps(metadata, indent=2) + "\n").encode("utf-8")
    if collect(root) != files:
        raise ValueError("Fixture inventory changed during generation")
    for path, content in ((output, bundle), (manifest, encoded_metadata)):
        if check:
            if not path.is_file() or path.read_bytes() != content:
                raise ValueError("Stale fixture bundle/inventory: " + str(path))
        else:
            path.write_bytes(content)
    return len(files)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        count = build(FIXTURES, OUTPUT, MANIFEST, check=args.check)
    except (OSError, ValueError) as error:
        parser.exit(1, f"{error}\nRun python3 tool/build_conformance_fixtures.py\n")
    print(f"Conformance fixture bundle: {count} files verified")


if __name__ == "__main__":
    main()
