"""Schema descriptors for the bounded Dart wire validator."""
import re


def validation_schema(source):
    source = re.sub(r"//[^\n]*", "", source)
    widths = {"bool": 1, "byte": 1, "ubyte": 1, "int8": 1, "uint8": 1,
              "short": 2, "ushort": 2, "int16": 2, "uint16": 2,
              "int": 4, "uint": 4, "int32": 4, "uint32": 4,
              "long": 8, "ulong": 8, "int64": 8, "uint64": 8,
              "float": 4, "double": 8}
    enums = {}
    for name, base, body in re.findall(r"enum\s+(\w+)\s*:\s*(\w+)\s*\{([^}]*)\}", source):
        values, value = [], 0
        for item in body.split(","):
            if not item.strip():
                continue
            parts = item.strip().split("=")
            if len(parts) == 2:
                value = int(parts[1].strip(), 0)
            values.append(value)
            value += 1
        enums[name] = (widths[base], values)
    tables = re.findall(r"table\s+(\w+)\s*\{([^}]*)\}", source)
    indices = {name: index for index, (name, _) in enumerate(tables)}
    unions = {name: [indices[item.strip().split(".")[-1]]
                     for item in body.split(",") if item.strip()]
              for name, body in re.findall(r"union\s+(\w+)\s*\{([^}]*)\}", source)}
    result = ["// Generated by tool/generate_wamp_flatbuffers.py; do not edit.",
              "import '../validation_types.dart';", "",
              f"const wampRootTable = {indices['Message']};",
              "const wampValidationTables = <FlatBufferTableSpec>["]
    for name, body in tables:
        result.append(f"  FlatBufferTableSpec('{name}', [")
        for field in body.split(";"):
            field = field.strip()
            if not field:
                continue
            match = re.fullmatch(r"(\w+)\s*:\s*(\[[\w.]+\]|[\w.]+)(?:\s*=\s*[\w.+-]+)?(?:\s*\(([^)]*)\))?", field)
            if not match:
                raise ValueError(f"Unsupported validation field: {name}.{field}")
            fname, ftype, attributes = match.groups()
            required = 'required' in {item.strip() for item in (attributes or '').split(',')}
            vector = ftype.startswith('[')
            base = ftype.strip('[]').split('.')[-1]
            values, reference, integer, width = [], -1, 'false', 4
            if base in unions:
                if vector:
                    raise ValueError("Union vectors require a dedicated validator")
                result.append(f"    FlatBufferFieldSpec('{fname}_type', FlatBufferFieldKind.scalar, 1, values: {list(range(len(unions[base]) + 1))}),")
                kind = 'union'
                values = [-1] + unions[base]
            elif base in enums or base in widths:
                width, values = enums.get(base, (widths.get(base), []))
                if base == 'bool':
                    values = [0, 1]
                integer = 'true' if base in ('uint64', 'ulong') else 'false'
                kind = 'scalarVector' if vector else 'scalar'
            elif base == 'string':
                kind = 'stringVector' if vector else 'string'
            elif base in indices:
                reference = indices[base]
                kind = 'tableVector' if vector else 'table'
            else:
                raise ValueError(f"Unsupported validation type: {base}")
            extras = []
            if required:
                extras.append('required: true')
            if reference != -1:
                extras.append(f'reference: {reference}')
            if values:
                extras.append(f'values: {values}')
            if integer == 'true':
                extras.append('wampInteger: true')
            suffix = ', ' + ', '.join(extras) if extras else ''
            result.append(f"    FlatBufferFieldSpec('{fname}', FlatBufferFieldKind.{kind}, {width}{suffix}),")
        result.append("  ]),")
    result.extend(["];"])
    return '\n'.join(result) + '\n'
