import 'dart:async';

import 'abstract_message.dart';
import 'event.dart';
import 'message_types.dart';

/// Is returned by the subscription process
class Subscribed extends AbstractMessage {
  int subscribeRequestId;
  int subscriptionId;
  Stream<Event>? _eventStreamOverride;
  StreamController<Event>? _eventController;
  StreamSubscription<Event>? _streamEventSubscription;
  void Function(Event event)? _onEvent;
  void Function(EventPayload event)? _onEventPayload;
  void Function(LazyEventPayload event)? _onLazyEventPayload;

  /// the constructor with a [subscribeRequestId] initially sent to the server
  /// and a [subscriptionId] that was generated by the server
  Subscribed(this.subscribeRequestId, this.subscriptionId) {
    id = MessageTypes.codeSubscribed;
  }

  /// Is created by the protocol processor and will receive an event object
  /// when the transport receives one
  Stream<Event>? get eventStream {
    return _eventStreamOverride ??
        (_eventController ??= _newEventController()).stream;
  }

  set eventStream(Stream<Event>? eventStream) {
    _eventStreamOverride = eventStream;
    _attachStreamEventHandlerIfNeeded();
  }

  final _revokeCompleter = Completer<String>();

  /// Is completed when the revocation happens
  Future<String> get onRevoke {
    return _revokeCompleter.future;
  }

  /// Is called by the session when the revocation happens
  void revoke(String? reason) {
    _revokeCompleter.complete(reason);
  }

  void onEvent(void Function(Event event) onEvent) {
    _onEvent = onEvent;
    _attachStreamEventHandlerIfNeeded();
  }

  void onEventPayload(void Function(EventPayload event) onEvent) {
    _onEventPayload = onEvent;
  }

  void onLazyEventPayload(void Function(LazyEventPayload event) onEvent) {
    _onLazyEventPayload = onEvent;
  }

  bool get hasMaterializedEventConsumers =>
      _onEvent != null || _eventController != null;

  bool get hasPayloadEventHandler => _onEventPayload != null;

  bool get hasLazyPayloadEventHandler => _onLazyEventPayload != null;

  void addEvent(Event event) {
    _onLazyEventPayload?.call(event.toLazyEventPayload(anchor: event));
    _onEventPayload?.call(event.toPayload());
    _deliverMaterializedEvent(event);
  }

  void addEventPayload(EventPayload event) {
    _onEventPayload?.call(event);
  }

  void addLazyEventPayload(LazyEventPayload event) {
    _onLazyEventPayload?.call(event);
    _onEventPayload?.call(event.toPayload());
  }

  void _deliverMaterializedEvent(Event event) {
    final onEvent = _onEvent;
    if (onEvent != null) {
      onEvent(event);
    }
    _eventController?.add(event);
  }

  Future<void> closeEventStream() async {
    await _streamEventSubscription?.cancel();
    _streamEventSubscription = null;
    final controller = _eventController;
    _eventController = null;
    if (controller != null && !controller.isClosed) {
      await controller.close();
    }
  }

  void _attachStreamEventHandlerIfNeeded() {
    if (_onEvent == null ||
        _eventStreamOverride == null ||
        _streamEventSubscription != null) {
      return;
    }
    _streamEventSubscription = _eventStreamOverride!.listen(_onEvent!);
  }

  StreamController<Event> _newEventController() {
    return StreamController<Event>.broadcast(sync: true);
  }
}
