name: connectanum_auth_server
description: Remote authentication server for Connectanum routers and clients.
version: 3.0.0-beta
homepage: https://github.com/konsultaner/connectanum-dart
repository: https://github.com/konsultaner/connectanum-dart
issue_tracker: https://github.com/konsultaner/connectanum-dart/issues

environment:
  sdk: '^3.9.2'

dependencies:
  args: ^2.5.0
  connectanum_router: ^3.0.0-beta
  connectanum_core: ^3.0.0-beta

dev_dependencies:
  test: ^1.25.0
resolution: workspace
