name: connectanum_auth_server
description: Remote authentication server for Connectanum routers and clients.
version: 0.1.0
homepage: https://github.com/konsultaner/connectanum-dart
repository: https://github.com/konsultaner/connectanum-dart
issue_tracker: https://github.com/konsultaner/connectanum-dart/issues
publish_to: 'none'

environment:
  sdk: '^3.9.2'

dependencies:
  args: ^2.5.0
  connectanum_router:
    path: ../connectanum_router
  connectanum_core:
    path: ../connectanum_core

dev_dependencies:
  test: ^1.25.0
resolution: workspace
